apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: admin
  name: admin
spec:
  ports:
  - name: "8989"
    port: 8989
    targetPort: 443
  selector:
    io.kompose.service: admin
status:
  loadBalancer: {}
