apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: adminer
  name: adminer
  namespace: librareome
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: adminer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: adminer
    spec:
      containers:
      - image: adminer
        imagePullPolicy: ""
        name: adminer
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "8Gi"
            cpu: "1"
          requests:
            memory: "100Mi"
            cpu: "500m"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
