apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hubs
  name: hubs
  namespace: librareome
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 443
  selector:
    io.kompose.service: hubs
status:
  loadBalancer: {}
