apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hubs
  name: hubs
  namespace: librareome
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hubs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: hubs
    spec:
      containers:
      - image: gitlab-registry.nautilus.optiputer.net/ar-noc/hubs
        env:
        - name: HOST
          value: "hubs.nautilus.optiputer.net"
        - name: RETICULUM_SOCKET_SERVER
          value: "hubs.nautilus.optiputer.net"
        - name: CORS_PROXY_SERVER
          value: "hubs-proxy:4000"
        - name: NON_CORS_PROXY_DOMAINS
          value: "hubs.nautilus.optiputer.net,dev.reticulum.io"
        - name: BASE_ASSETS_PATH
          value: "https://hubs.nautilus.optiputer.net:8989/"
        - name: RETICULUM_SERVER
          value: "hubs:4000"
        - name: POSTGREST_SERVER
          value: "db"
        - name: ITA_SERVER
          value: ""
        command: ["ash", "-c"]
#        args: ["sleep infinity"]
#        args: ["npm run login && yarn start"]
        args: ["npm run dev"]
        imagePullPolicy: ""
        name: hubs
        ports:
        - containerPort: 443
        resources:
          limits:
            memory: "8Gi"
            cpu: "1"
          requests:
            memory: "100Mi"
            cpu: "500m"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
