apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: janus
  name: janus
  namespace: librareome
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: janus
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: janus
    spec:
      containers:
      - image: janus
        imagePullPolicy: ""
        name: janus
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
