apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: reticulum
  name: reticulum
  namespace: librareome
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reticulum
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: reticulum
    spec:
      containers:
      - env:
        - name: ADMIN_HOST
          value: hubs
        - name: ADMIN_PORT
          value: "444"
        - name: DB_HOST
          value: db
        - name: HUBS_HOST
          value: hubs
        - name: HUBS_PORT
          value: "443"
        - name: MIX_ENV
          value: dev
        - name: SPOKE_HOST
          value: spoke
        - name: SPOKE_PORT
          value: "80"
        image: mozzila-reticulum
        imagePullPolicy: ""
        name: reticulum
        ports:
        - containerPort: 4000
        resources:
          limits:
            memory: "8Gi"
            cpu: "1"
          requests:
            memory: "100Mi"
            cpu: "500m"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
