apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: reverse-proxy
  name: reverse-proxy
  namespace: librareome
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reverse-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: reverse-proxy
    spec:
      containers:
      - args:
        - --api.insecure=true
        - --providers.docker
        image: traefik:v2.1
        imagePullPolicy: ""
        name: reverse-proxy
        ports:
        - containerPort: 80
        - containerPort: 8080
        resources:
          limits:
            memory: "8Gi"
            cpu: "1"
          requests:
            memory: "100Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: reverse-proxy-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: reverse-proxy-claim0
        persistentVolumeClaim:
          claimName: reverse-proxy-claim0
status: {}
