apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spoke
  name: spoke
  namespace: librareome
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spoke
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: spoke
    spec:
      containers:
      - env:
        - name: HOST
          value: '"hubs.local"'
        image: spoke
        imagePullPolicy: ""
        name: spoke
        ports:
        - containerPort: 433
        resources:
          limits:
            memory: "8Gi"
            cpu: "1"
          requests:
            memory: "100Mi"
            cpu: "500m"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
